export const cleanPhrases = [
  // ============================================================
  // TEMPERATURE-ONLY (70 phrases) - conditions: ["any"]
  // ============================================================
  { text: "It's [temp] degrees. That's not a temperature, that's a dare.", conditions: ["any"], tempRange: [85, 95], priority: 1 },
  { text: "[temp] degrees. Your thermostat is judging you right now.", conditions: ["any"], tempRange: [60, 80], priority: 1 },
  { text: "A perfectly mediocre [temp] degrees. The weather equivalent of elevator music.", conditions: ["any"], tempRange: [55, 70], priority: 1 },
  { text: "[temp] degrees out there. Dress in layers or regret everything.", conditions: ["any"], tempRange: [35, 50], priority: 1 },
  { text: "It's [temp] degrees. That hoodie-or-no-hoodie dilemma is back.", conditions: ["any"], tempRange: [58, 68], priority: 2 },
  { text: "[temp] degrees. Not cold enough for sympathy, not warm enough for comfort.", conditions: ["any"], tempRange: [40, 55], priority: 1 },
  { text: "At [temp] degrees, your car seats are either lava or ice. No in-between.", conditions: ["any"], tempRange: [30, 95], priority: 1 },
  { text: "[temp] degrees and your weather app thinks you needed to know that.", conditions: ["any"], tempRange: null, priority: 1 },
  { text: "A thrilling [temp] degrees. Try to contain your excitement.", conditions: ["any"], tempRange: [45, 65], priority: 1 },
  { text: "It's [temp] degrees. Perfect for doing absolutely nothing outside.", conditions: ["any"], tempRange: [85, 100], priority: 1 },
  { text: "[temp] degrees. Somewhere between 'fine' and 'I guess this is fine.'", conditions: ["any"], tempRange: [50, 70], priority: 1 },
  { text: "The current temperature is [temp] degrees, which is a number that exists.", conditions: ["any"], tempRange: null, priority: 1 },
  { text: "[temp] degrees. Your dog wants to go outside. Your dog is wrong.", conditions: ["any"], tempRange: [90, 110], priority: 2 },
  { text: "It's a balmy [temp] degrees if you're a penguin.", conditions: ["any"], tempRange: [10, 30], priority: 1 },
  { text: "[temp] degrees. The kind of weather that makes you question your zip code.", conditions: ["any"], tempRange: null, priority: 1 },
  { text: "At [temp] degrees, iced coffee becomes a survival tool.", conditions: ["any"], tempRange: [80, 100], priority: 1 },
  { text: "[temp] degrees. Hot coffee weather has officially arrived.", conditions: ["any"], tempRange: [25, 45], priority: 1 },
  { text: "Currently [temp] degrees. That's room temperature if your room is outside.", conditions: ["any"], tempRange: [68, 76], priority: 1 },
  { text: "[temp] degrees. Nature can't decide what season it is either.", conditions: ["any"], tempRange: [50, 65], priority: 1 },
  { text: "The thermometer reads [temp] degrees. The thermometer is not your friend today.", conditions: ["any"], tempRange: [90, 115], priority: 1 },
  { text: "It's [temp] degrees. Your grandpa called it 'brisk.' Your grandpa was tough.", conditions: ["any"], tempRange: [15, 35], priority: 2 },
  { text: "[temp] degrees. Acceptable. Not great. Just... acceptable.", conditions: ["any"], tempRange: [55, 70], priority: 1 },
  { text: "At [temp] degrees your lips will chap just thinking about going outside.", conditions: ["any"], tempRange: [5, 25], priority: 1 },
  { text: "[temp] degrees. The only thing getting toasted today is you.", conditions: ["any"], tempRange: [88, 105], priority: 1 },
  { text: "Oh look, [temp] degrees. The temperature of mild inconvenience.", conditions: ["any"], tempRange: [38, 50], priority: 1 },
  { text: "[temp] degrees and dropping, much like your motivation.", conditions: ["any"], tempRange: [20, 40], priority: 1 },
  { text: "It's [temp] degrees. Flip-flop people and boot people are both outside right now.", conditions: ["any"], tempRange: [55, 65], priority: 2 },
  { text: "[temp] degrees. Not the worst thing to happen today. Probably.", conditions: ["any"], tempRange: null, priority: 1 },
  { text: "Currently [temp] degrees. Your outfit was wrong the moment you chose it.", conditions: ["any"], tempRange: [45, 60], priority: 1 },
  { text: "[temp] degrees. This is the weather equivalent of a participation trophy.", conditions: ["any"], tempRange: [50, 68], priority: 1 },
  // --- 40 NEW temperature-only phrases ---
  { text: "It's [temp] degrees and honestly nobody asked for this.", conditions: ["any"], tempRange: null, priority: 1 },
  { text: "[temp] degrees. Your body can't decide if it wants the AC or the heater.", conditions: ["any"], tempRange: [55, 68], priority: 1 },
  { text: "A bold [temp] degrees outside. Bold and unwelcome.", conditions: ["any"], tempRange: [85, 100], priority: 1 },
  { text: "[temp] degrees. The weather is gaslighting you into thinking spring exists.", conditions: ["any"], tempRange: [42, 58], priority: 1 },
  { text: "It's [temp] degrees and the grocery store parking lot is a proving ground.", conditions: ["any"], tempRange: [88, 105], priority: 1 },
  { text: "[temp] degrees. Your morning commute just became a character arc.", conditions: ["any"], tempRange: [10, 30], priority: 1 },
  { text: "Currently [temp] degrees. The perfect temperature for complaining.", conditions: ["any"], tempRange: null, priority: 2 },
  { text: "[temp] degrees. Somewhere a weather forecaster is calling this 'pleasant.'", conditions: ["any"], tempRange: [72, 80], priority: 1 },
  { text: "It's [temp] degrees out. Your pet is judging you from the window.", conditions: ["any"], tempRange: [80, 95], priority: 1 },
  { text: "[temp] degrees. You will overdress. Or underdress. There is no correct answer.", conditions: ["any"], tempRange: [48, 62], priority: 1 },
  { text: "At [temp] degrees you can technically sit on a park bench. Technically.", conditions: ["any"], tempRange: [35, 48], priority: 1 },
  { text: "[temp] degrees and the vending machine coffee finally makes sense.", conditions: ["any"], tempRange: [20, 38], priority: 1 },
  { text: "It's [temp] degrees. Your coworker is still wearing shorts.", conditions: ["any"], tempRange: [30, 45], priority: 2 },
  { text: "[temp] degrees. That's a temperature that exists purely to inconvenience you.", conditions: ["any"], tempRange: [43, 57], priority: 1 },
  { text: "A breezy [temp] degrees, which means your nose will run at the crosswalk.", conditions: ["any"], tempRange: [32, 45], priority: 1 },
  { text: "[temp] degrees. Perfect weather for a blanket burrito.", conditions: ["any"], tempRange: [15, 35], priority: 1 },
  { text: "It's [temp] degrees and the only thing thriving is your electric bill.", conditions: ["any"], tempRange: [90, 110], priority: 1 },
  { text: "[temp] degrees. Your iced latte is now room-temp latte in four minutes.", conditions: ["any"], tempRange: [85, 100], priority: 1 },
  { text: "A riveting [temp] degrees. The weather is truly phoning it in.", conditions: ["any"], tempRange: [60, 72], priority: 1 },
  { text: "[temp] degrees and everyone at the office is fighting over the thermostat.", conditions: ["any"], tempRange: [68, 78], priority: 2 },
  { text: "It's [temp] degrees. Not enough to cancel plans, just enough to resent them.", conditions: ["any"], tempRange: [36, 48], priority: 1 },
  { text: "[temp] degrees. The kind of cold that makes your steering wheel feel personal.", conditions: ["any"], tempRange: [10, 28], priority: 1 },
  { text: "Currently [temp] degrees. Your weather app delivered this news with zero empathy.", conditions: ["any"], tempRange: null, priority: 1 },
  { text: "[temp] degrees out. Warm enough that your chocolate bar in the car is a puddle now.", conditions: ["any"], tempRange: [80, 95], priority: 1 },
  { text: "It's [temp] degrees. Go ahead and cancel that jog you were never going to take.", conditions: ["any"], tempRange: [88, 105], priority: 1 },
  { text: "[temp] degrees. The great jacket debate of the morning begins.", conditions: ["any"], tempRange: [50, 64], priority: 1 },
  { text: "A stunning [temp] degrees, if you're into that sort of thing.", conditions: ["any"], tempRange: [70, 82], priority: 1 },
  { text: "[temp] degrees. The temp where you keep checking the weather hoping it changed.", conditions: ["any"], tempRange: [38, 52], priority: 1 },
  { text: "It's [temp] degrees and your car's leather seats have chosen violence.", conditions: ["any"], tempRange: [90, 115], priority: 1 },
  { text: "[temp] degrees. Cold enough for soup, warm enough for guilt about not going outside.", conditions: ["any"], tempRange: [40, 55], priority: 1 },
  { text: "At [temp] degrees your glasses fog up the second you walk inside.", conditions: ["any"], tempRange: [15, 32], priority: 1 },
  { text: "[temp] degrees. Working from home has never felt more justified.", conditions: ["any"], tempRange: [95, 115], priority: 2 },
  { text: "It's [temp] degrees. That's a whole mood and it's not a good one.", conditions: ["any"], tempRange: null, priority: 1 },
  { text: "[temp] degrees. The weather is giving 'I don't care about your plans.'", conditions: ["any"], tempRange: null, priority: 1 },
  { text: "A casual [temp] degrees. Your sweatpants understand.", conditions: ["any"], tempRange: [55, 68], priority: 1 },
  { text: "[temp] degrees. Hot enough to melt your will to cook dinner.", conditions: ["any"], tempRange: [88, 100], priority: 1 },
  { text: "It's [temp] degrees and your popsicle has about thirty seconds.", conditions: ["any"], tempRange: [85, 105], priority: 1 },
  { text: "[temp] degrees. Your car said 'check engine' but it meant 'check yourself.'", conditions: ["any"], tempRange: [5, 20], priority: 1 },
  { text: "Currently [temp] degrees. Every dog walker looks like they regret their choices.", conditions: ["any"], tempRange: [90, 110], priority: 1 },
  { text: "[temp] degrees. Somehow both too warm and too cold for what you're wearing.", conditions: ["any"], tempRange: [58, 68], priority: 1 },

  // ============================================================
  // CLEAR/SUNNY (60 phrases)
  // ============================================================
  { text: "Oh good, another beautiful day to spend staring at a screen.", conditions: ["clear"], tempRange: null, priority: 2 },
  { text: "Clear skies. The sun is out and it has zero respect for your pale skin.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Gorgeous day outside. Your office window is really rubbing it in.", conditions: ["clear"], tempRange: null, priority: 2 },
  { text: "Not a cloud in the sky. Sunglasses aren't optional, they're survival gear.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Picture-perfect weather. Everyone on social media will make sure you know.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Beautiful clear day. Your sunburn is already in progress.", conditions: ["clear"], tempRange: [75, 95], priority: 1 },
  { text: "The sky is aggressively blue today. Almost suspiciously so.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Sunny and clear. Nature is showing off and honestly it's annoying.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "It's a perfect day. Go outside or feel guilty about it for the rest of the week.", conditions: ["clear"], tempRange: [65, 80], priority: 2 },
  { text: "Clear skies and sunshine. Your vitamin D levels are begging you to go outside.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Cloudless sky. Your car's interior is now a convection oven.", conditions: ["clear"], tempRange: [80, 100], priority: 1 },
  { text: "The sun is out and absolutely unhinged today.", conditions: ["clear"], tempRange: [85, 100], priority: 1 },
  { text: "Stunning weather. The kind of day that tricks you into making outdoor plans.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Blue skies everywhere. Your allergies don't care.", conditions: ["clear"], tempRange: [60, 85], priority: 1 },
  { text: "Perfectly sunny. The dashboard of your car could fry an egg.", conditions: ["clear"], tempRange: [85, 100], priority: 1 },
  { text: "Clear and bright. Time to discover which of your windows need cleaning.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Not a single cloud showed up for work today.", conditions: ["clear"], tempRange: null, priority: 2 },
  { text: "Sunshine like the weather is trying to make up for last week.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "The sky is so clear you can see your regret for not planning a beach day.", conditions: ["clear"], tempRange: [70, 90], priority: 1 },
  { text: "It's sunny. Go touch grass. Literally.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "A flawless clear day. Your air conditioner is preparing for battle.", conditions: ["clear"], tempRange: [85, 100], priority: 1 },
  { text: "Bright and sunny out there. Your freckles are about to multiply.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "What a beautiful day to realize you forgot to buy sunscreen.", conditions: ["clear"], tempRange: [75, 95], priority: 2 },
  { text: "The sun is absolutely doing its job today. No notes.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Crystal clear skies. The moon is jealous.", conditions: ["clear"], tempRange: null, priority: 1 },
  // --- 35 NEW clear/sunny phrases ---
  { text: "Sunny enough that your sunglasses tan line is coming back.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "The sun is out and your laundry is drying faster than your motivation.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Clear skies. Perfect day to pretend you're going to go for a hike.", conditions: ["clear"], tempRange: null, priority: 2 },
  { text: "Sunshine is pouring in and your houseplants are having the best day of their lives.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "It's gorgeous outside and your to-do list is staring at you with disappointment.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Clear skies, bright sun, and you're about to walk into a glass door because of the glare.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "The sun showed up with the energy of someone who slept nine hours.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "It's so sunny the GPS screen in your car is now invisible.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Another aggressively beautiful day. Your couch is calling anyway.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Clear day. Every neighbor you've been avoiding is definitely outside.", conditions: ["clear"], tempRange: null, priority: 2 },
  { text: "The sun is performing today. Standing ovation from your garden.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Sunny and gorgeous. Your dog is already pulling toward the door.", conditions: ["clear"], tempRange: [60, 80], priority: 1 },
  { text: "Perfect weather for a picnic you will plan but never execute.", conditions: ["clear"], tempRange: [65, 82], priority: 1 },
  { text: "It's so clear outside the sky looks photoshopped.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "The sun is shining directly into your soul and your living room.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Blue sky as far as the eye can see. Your hay fever has entered the chat.", conditions: ["clear"], tempRange: [55, 80], priority: 1 },
  { text: "Sunny day. Time to discover every smudge on your windshield.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "It's beautiful outside. The pressure to enjoy it is suffocating.", conditions: ["clear"], tempRange: null, priority: 2 },
  { text: "Clear skies. Your solar panels are thriving. You, less so.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Bright sunshine today. Every spider web on your porch is suddenly visible.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "The kind of sunny day that makes you reconsider your life as an indoor person.", conditions: ["clear"], tempRange: [68, 82], priority: 1 },
  { text: "It's clear and sunny and you still forgot to water the plants.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Sunny out. Your ice cream cone has approximately ninety seconds.", conditions: ["clear"], tempRange: [80, 95], priority: 1 },
  { text: "Not a cloud anywhere. Nature is flexing.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Brilliant sunshine. Your eyes are paying the price for leaving sunglasses at home.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Perfect clear day. The kind where you open the window and immediately regret allergies.", conditions: ["clear"], tempRange: [60, 78], priority: 1 },
  { text: "Sunny enough that your steering wheel could brand livestock.", conditions: ["clear"], tempRange: [85, 100], priority: 1 },
  { text: "The weather is perfect, which means everyone and their family is at the park.", conditions: ["clear"], tempRange: [65, 80], priority: 1 },
  { text: "Relentlessly sunny. Even the shade is warm.", conditions: ["clear"], tempRange: [82, 95], priority: 1 },
  { text: "Clear skies and pure sunshine. Your excuses for staying inside just evaporated.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Absolutely stunning day. Wasted on a Tuesday.", conditions: ["clear"], tempRange: null, priority: 2 },
  { text: "The sun came out swinging and your patio furniture is ready.", conditions: ["clear"], tempRange: null, priority: 1 },
  { text: "Perfect sunny day. Your grocery list just expanded to include charcoal and burgers.", conditions: ["clear"], tempRange: [70, 85], priority: 1 },
  { text: "Not a single excuse to skip the farmers market today.", conditions: ["clear"], tempRange: [58, 78], priority: 1 },
  { text: "Sunshine is aggressive. The visor in your car is working overtime.", conditions: ["clear"], tempRange: null, priority: 1 },

  // ============================================================
  // RAIN (50 phrases)
  // ============================================================
  { text: "It's raining. Your windshield wipers have entered the chat.", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 1 },
  { text: "Rain. Because you washed your car yesterday, didn't you.", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 2 },
  { text: "Currently raining. Your umbrella is at home where it's safe and dry.", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 2 },
  { text: "The sky is leaking again. Someone should file a maintenance request.", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 1 },
  { text: "Heavy rain. Your socks are about to have a really bad time.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "Light drizzle. Just enough to ruin your hair but not enough for an umbrella.", conditions: ["drizzle"], tempRange: null, priority: 2 },
  { text: "Pouring rain. Good day to pretend you're in a sad music video.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "It's raining sideways. Even your raincoat is confused.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "Rain all day. Your plans just became 'indoor plans.'", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 1 },
  { text: "The rain is really committed today. Respect, honestly.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "Drizzling outside. The most passive-aggressive form of rain.", conditions: ["drizzle"], tempRange: null, priority: 2 },
  { text: "Rain is hammering down. Your patio furniture is going on an adventure.", conditions: ["heavy-rain"], tempRange: null, priority: 1 },
  { text: "It's wet out there. Really, spectacularly, aggressively wet.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "The clouds are ugly-crying today.", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 1 },
  { text: "Raining just enough to make every parking lot a slip hazard.", conditions: ["rain", "drizzle"], tempRange: null, priority: 1 },
  { text: "Rain. Cancel everything. Stay home. Watch something. You deserve it.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "Every puddle is a trap. Trust nothing.", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 1 },
  { text: "Rain so heavy your wipers just gave up and filed for retirement.", conditions: ["heavy-rain"], tempRange: null, priority: 1 },
  { text: "Drizzle that somehow gets you wetter than actual rain.", conditions: ["drizzle"], tempRange: null, priority: 1 },
  { text: "Raining. Your dog looked outside and went back to bed. Smart dog.", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 1 },
  // --- 30 NEW rain phrases ---
  { text: "It's raining and your hair straightener just lost the war.", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 1 },
  { text: "Rain today. Perfect excuse to order delivery for every meal.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 2 },
  { text: "Pouring outside. Your suede shoes are filing a grievance.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "Drizzle so fine it's basically atmosphere with an attitude.", conditions: ["drizzle"], tempRange: null, priority: 1 },
  { text: "Raining hard enough that your grocery run feels like a Navy SEAL mission.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "The rain is coming down like it has something to prove.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "It's raining. Your freshly mopped floors don't stand a chance.", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 1 },
  { text: "Wet commute today. Every driver has forgotten what turn signals are.", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 1 },
  { text: "Rain so steady it's basically a lifestyle at this point.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "Drizzle. The weather's way of being annoying without fully committing.", conditions: ["drizzle"], tempRange: null, priority: 1 },
  { text: "Heavy rain and your gutters are auditioning for a waterfall documentary.", conditions: ["heavy-rain"], tempRange: null, priority: 1 },
  { text: "Raining. Your mailbox is now a small swimming pool.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "It's raining and every crosswalk puddle is ankle-deep. Choose wisely.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "The rain is relentless. So is your desire to stay in bed.", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 1 },
  { text: "Downpour outside. Your dash to the car door will be a sprint.", conditions: ["heavy-rain"], tempRange: null, priority: 1 },
  { text: "Raining. The one day you wore white. Of course.", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 2 },
  { text: "It's raining and the pothole on your street is now a lake.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "Light rain. Heavy regret for leaving the window cracked.", conditions: ["rain", "drizzle"], tempRange: null, priority: 1 },
  { text: "It's pouring. Your outdoor cat is giving you the most betrayed look.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "Rain all damn day. Your umbrella collection is about to be tested.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "Drizzle turning to rain. Nature is warming up for the main event.", conditions: ["drizzle", "rain"], tempRange: null, priority: 1 },
  { text: "The parking lot is now a splash zone. You have been warned.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "Raining. Every umbrella in the office is someone else's today.", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 1 },
  { text: "It's raining and your car windows are still down. Run.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 2 },
  { text: "Heavy rain. The kind where you sit in the car and wait before going inside.", conditions: ["heavy-rain"], tempRange: null, priority: 1 },
  { text: "Rain on your commute. The podcast better be good today.", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 1 },
  { text: "A gentle drizzle that makes everything look cinematic but feel damp.", conditions: ["drizzle"], tempRange: null, priority: 1 },
  { text: "Raining. Your work-from-home setup suddenly looks like the right call.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },
  { text: "It's raining and the dog still expects a walk. The dog is delusional.", conditions: ["rain", "heavy-rain", "drizzle"], tempRange: null, priority: 1 },
  { text: "Rain hitting the roof like it's trying to get your attention.", conditions: ["rain", "heavy-rain"], tempRange: null, priority: 1 },

  // ============================================================
  // SNOW (40 phrases)
  // ============================================================
  { text: "It's snowing. Somewhere a kid is thrilled. That kid isn't you.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 2 },
  { text: "Snow day vibes, except you still have to work.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 2 },
  { text: "Heavy snow. Your commute just became an expedition.", conditions: ["heavy-snow"], tempRange: null, priority: 1 },
  { text: "Snowing like Mother Nature emptied a giant snow globe.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 1 },
  { text: "Light snow falling. Pretty for about five minutes, then it's just cold nonsense.", conditions: ["snow"], tempRange: null, priority: 1 },
  { text: "Snow everywhere. Your shovel is somewhere in the garage. Good luck.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 1 },
  { text: "The world is white and your driveway is a problem.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 1 },
  { text: "Snowing hard. Bread and milk sales just spiked.", conditions: ["heavy-snow"], tempRange: null, priority: 1 },
  { text: "A winter wonderland. Also known as 'where did I park my car?'", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 2 },
  { text: "Snow is falling gently, which is nature's way of saying 'surprise ice later.'", conditions: ["snow"], tempRange: null, priority: 1 },
  { text: "Blizzard conditions. Your couch has never been more appealing.", conditions: ["heavy-snow"], tempRange: null, priority: 1 },
  { text: "It's snowing and every driver has collectively forgotten how to drive.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 1 },
  { text: "Fresh snow. Beautiful, quiet, and about to turn into brown slush by noon.", conditions: ["snow"], tempRange: null, priority: 1 },
  { text: "Snow is piling up. Your back hurts just looking at it.", conditions: ["heavy-snow"], tempRange: null, priority: 1 },
  { text: "Snowflakes are falling like nature's dandruff.", conditions: ["snow"], tempRange: null, priority: 1 },
  // --- 25 NEW snow phrases ---
  { text: "It's snowing and your car is slowly becoming an igloo.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 1 },
  { text: "Heavy snow. Time to pretend you're snowed in even if you're not.", conditions: ["heavy-snow"], tempRange: null, priority: 2 },
  { text: "Snow on the roads. Every intersection is now a trust exercise.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 1 },
  { text: "Snowing. Your neighbor's kid already has a snowball with your name on it.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 1 },
  { text: "Light snow falling. Your windshield scraper is buried under six other things in the trunk.", conditions: ["snow"], tempRange: null, priority: 1 },
  { text: "Heavy snow advisory. Your Amazon packages are having an adventure.", conditions: ["heavy-snow"], tempRange: null, priority: 1 },
  { text: "It's snowing sideways. Even the snowplow driver looks concerned.", conditions: ["heavy-snow"], tempRange: null, priority: 1 },
  { text: "Snow day. The coffee is hot, the blankets are warm, and your inbox can wait.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 2 },
  { text: "Snowing hard enough to justify canceling literally anything.", conditions: ["heavy-snow"], tempRange: null, priority: 1 },
  { text: "Fresh snow makes everything look peaceful. Give it an hour.", conditions: ["snow"], tempRange: null, priority: 1 },
  { text: "It's snowing and your boots are by the wrong door. Of course they are.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 1 },
  { text: "Snow is falling like someone shook the planet.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 1 },
  { text: "Snowing. The parking lot lines are now merely a suggestion.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 1 },
  { text: "Heavy snow. Your mailman deserves a medal today.", conditions: ["heavy-snow"], tempRange: null, priority: 1 },
  { text: "Light snow that's just heavy enough to frost your entire windshield.", conditions: ["snow"], tempRange: null, priority: 1 },
  { text: "It's snowing and every school bus is running ten minutes late.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 1 },
  { text: "Snow. The kids are excited. The adults are doing math on the salt supply.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 1 },
  { text: "Blizzard-level snow. Your front door is now a snow fort entrance.", conditions: ["heavy-snow"], tempRange: null, priority: 1 },
  { text: "It's snowing and your driveway just reset to hard mode.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 2 },
  { text: "Snow is accumulating like unread emails.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 1 },
  { text: "Snowing. The sidewalk you shoveled an hour ago would like a word.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 1 },
  { text: "Heavy snow and your work-from-home request just became a lot more convincing.", conditions: ["heavy-snow"], tempRange: null, priority: 1 },
  { text: "It's snowing. Your hot cocoa consumption is about to triple.", conditions: ["snow", "heavy-snow"], tempRange: null, priority: 1 },
  { text: "Snow so thick you can't tell where the yard ends and the sidewalk begins.", conditions: ["heavy-snow"], tempRange: null, priority: 1 },
  { text: "Light snow that's pretty until you realize you have to drive in it.", conditions: ["snow"], tempRange: null, priority: 1 },

  // ============================================================
  // THUNDERSTORM (40 phrases)
  // ============================================================
  { text: "Thunderstorm rolling in. Mother Nature chose violence today.", conditions: ["thunderstorm"], tempRange: null, priority: 2 },
  { text: "Thunder and lightning. The sky is having a full breakdown.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "There's a thunderstorm and your pet is now in your lap whether you like it or not.", conditions: ["thunderstorm"], tempRange: null, priority: 2 },
  { text: "Lightning outside. The sky is taking flash photography.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Severe thunderstorm. A great time to unplug things and question your life choices.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Thunder so loud your house just flinched.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "The storm is here and it brought its whole crew.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Thunderstorm weather. Your power grid is about to play roulette.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Lightning is striking like the sky is sending angry texts.", conditions: ["thunderstorm"], tempRange: null, priority: 2 },
  { text: "Thunderstorm warning. Translation: charge your devices now.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "The sky is growling. It sounds personal.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "It's storming and your trash cans are now your neighbor's problem.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Heavy thunder outside. Every car alarm in the neighborhood agrees.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "The atmosphere is throwing a tantrum right now.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Thunderstorm in full effect. Your outdoor furniture is rearranging itself.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  // --- 25 NEW thunderstorm phrases ---
  { text: "Lightning just lit up your whole bedroom. Free alarm clock.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Thunder so close it rattled the dishes. The sky means business.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Thunderstorm outside. Your candle collection is finally relevant.", conditions: ["thunderstorm"], tempRange: null, priority: 2 },
  { text: "The storm sounds like the sky is rearranging furniture up there.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Lightning and thunder back to back. The sky has no patience today.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Severe storm rolling through. Your phone has sent four alerts and counting.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Thunderstorm. Your cat just achieved a land speed record getting under the bed.", conditions: ["thunderstorm"], tempRange: null, priority: 2 },
  { text: "The power flickered. Everyone in the house just held their breath.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Storm is raging. The wifi is hanging by a thread and so is your sanity.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Thunderstorm so intense the dog and the cat are cuddling. Historic.", conditions: ["thunderstorm"], tempRange: null, priority: 2 },
  { text: "Lightning show outside. Nature is providing free entertainment tonight.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "That thunder boom just made the whole neighborhood jump collectively.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Storm knocked out the power. Family board game night is no longer optional.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Thunderstorm warning in effect. Your outdoor plans just got permanently postponed.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "The thunder is so loud it reset every Ring doorbell on the block.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Lightning flash followed by immediate thunder. That one was close and personal.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Storm is howling outside. Your blanket fort has never been more strategic.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Thunderstorm vibes. The perfect background noise for doing absolutely nothing.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "The sky is putting on a show and your pets are not entertained.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Every clap of thunder sounds like the sky is slamming a door.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Storm is here. Your grill cover just became a kite.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Thunderstorm so dramatic it deserves its own soundtrack.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "The lightning is nonstop. Somewhere a transformer is having a bad night.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Thunder rolling across the sky like a bowling alley up there.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },
  { text: "Storm advisory. Translation: you're not going anywhere for a while.", conditions: ["thunderstorm"], tempRange: null, priority: 1 },

  // ============================================================
  // CLOUDY (40 phrases)
  // ============================================================
  { text: "Overcast skies. The sun called in sick.", conditions: ["cloudy"], tempRange: null, priority: 2 },
  { text: "Gray and gloomy. Today's aesthetic is 'meh.'", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Cloud cover at 100%. The sky is buffering.", conditions: ["cloudy"], tempRange: null, priority: 2 },
  { text: "Cloudy with a chance of existential dread.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "The clouds have formed a solid wall of disappointment today.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "It's gray outside. Real 'stare out the window and sigh' weather.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Fully overcast. Nature turned the brightness all the way down.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "The sky is the color of a dirty dishrag. Inspiring stuff.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Clouds everywhere. Even your mood is overcast.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Overcast skies like the world is wearing a gray hoodie.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Today's sky brought to you by the color blah.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Not a ray of sunshine in sight. The clouds are gatekeeping.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Gray skies again. Mother Nature is in her sad era.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Cloudy and dull. Much like that meeting on your calendar.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "The whole sky looks like it's about to cry but won't commit.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  // --- 25 NEW cloudy phrases ---
  { text: "Overcast all day. The sun ghosted everyone.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Gray skies. Even the birds look like they'd rather be somewhere else.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Cloudy. The kind of day that was built for sweatpants and regret.", conditions: ["cloudy"], tempRange: null, priority: 2 },
  { text: "The sky looks like it's loading but the progress bar isn't moving.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Completely overcast. Vitamin D is a distant memory.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Gray day. Your coffee consumption is about to double.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Cloudy enough to forget what time of day it is.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "The clouds showed up early and have no plans to leave.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Overcast skies. The weather is matching your inbox energy.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "It's so gray outside that turning on every light in the house feels justified.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Cloudy. Not dramatic enough for rain, not nice enough for a walk. Just... there.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "The sky is one giant cloud today. No variety. No effort.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Gray skies and your couch are forming an alliance against productivity.", conditions: ["cloudy"], tempRange: null, priority: 2 },
  { text: "Overcast and dull. The weather equivalent of being on hold.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Cloudy day. Even your phone's auto-brightness gave up.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "The clouds are just sitting there. Menacingly.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Gray and lifeless outside. Your houseplants are confused.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Overcast. The world looks like someone turned the saturation to zero.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Cloudy day. Third cup of coffee is now medically necessary.", conditions: ["cloudy"], tempRange: null, priority: 2 },
  { text: "The sky hasn't picked a personality all day. Just gray.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Overcast and heavy. The atmosphere is brooding.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Gray. Just aggressively, relentlessly gray.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Cloudy enough that your solar garden lights are completely useless.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "The clouds rolled in like they own the place.", conditions: ["cloudy"], tempRange: null, priority: 1 },
  { text: "Overcast. Your motivation left with the sun.", conditions: ["cloudy"], tempRange: null, priority: 1 },

  // ============================================================
  // FOG (32 phrases)
  // ============================================================
  { text: "Foggy out there. Your commute just became a horror movie.", conditions: ["fog"], tempRange: null, priority: 2 },
  { text: "Can't see a damn thing. The fog has entered the chat.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Fog so thick you could spread it on toast.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "It's foggy. If you see a lighthouse, you've gone too far.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "The fog is giving main character in a mystery novel.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Dense fog advisory. Translation: drive like you have no idea what's out there, because you don't.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Foggy enough that your headlights are purely decorative.", conditions: ["fog"], tempRange: null, priority: 2 },
  { text: "The world has been replaced by a cloud. Deal with it.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Fog everywhere. Your GPS is the only thing that knows where you are.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "It's so foggy the birds are walking.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Pea soup fog. The kind where you discover sidewalks by tripping on them.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Heavy fog rolling in. Visibility is 'good luck out there, champ.'", conditions: ["fog"], tempRange: null, priority: 1 },
  // --- 20 NEW fog phrases ---
  { text: "Fog so thick your neighbor's house just disappeared.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Foggy morning. Your high beams just made everything worse.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "The fog turned your street into a silent film set.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Can't see the end of the driveway. Adventure starts immediately.", conditions: ["fog"], tempRange: null, priority: 2 },
  { text: "Fog advisory. Your morning commute now requires a co-pilot and a prayer.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "It's foggy and every approaching car looks like a ghost until the last second.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "The fog is so dense your car's backup camera is just showing static.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Foggy enough that your front yard looks like a different dimension.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Visibility is approximately one shopping cart length.", conditions: ["fog"], tempRange: null, priority: 2 },
  { text: "The fog rolled in like it had an appointment.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Fog. The kind where you wave to a stranger who turns out to be a mailbox.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Foggy out. Your windshield wipers are doing their best but it's not enough.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Dense fog. Every stoplight is just a vague suggestion of color.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "The fog makes everything look eerie. Even the Starbucks looks haunted.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Fog so low the street signs are useless. Good luck finding your turn.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Foggy morning. The school bus just appeared out of nowhere like a jump scare.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "It's foggy and your glasses are foggier. Double fog.", conditions: ["fog"], tempRange: null, priority: 2 },
  { text: "The fog turned the parking lot into a game of Marco Polo.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Visibility is 'can you see your hand?' and the answer is barely.", conditions: ["fog"], tempRange: null, priority: 1 },
  { text: "Fog has swallowed the whole neighborhood. No one has been seen since.", conditions: ["fog"], tempRange: null, priority: 1 },

  // ============================================================
  // WIND (32 phrases)
  // ============================================================
  { text: "Windy as hell out there. Hold onto your hat. And your dog.", conditions: ["wind"], tempRange: null, priority: 2 },
  { text: "Wind so strong your car door just became a weapon.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "Your hair doesn't stand a chance today.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "Gusts strong enough to restructure your entire hairdo.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "The wind is absolutely unhinged today. Trash cans are migrating.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "Breezy is an understatement. Your recycling bin is in the next county.", conditions: ["wind"], tempRange: null, priority: 2 },
  { text: "Wind advisory in effect. Your patio umbrella has left the group chat.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "It's so windy that walking is now a competitive sport.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "The wind is rearranging your yard for free today.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "Gusting winds. Every door you open is a jump scare.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "Hurricane-adjacent vibes outside. Your flag is horizontal.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "The wind just body-checked a pedestrian. Stay sharp.", conditions: ["wind"], tempRange: null, priority: 1 },
  // --- 20 NEW wind phrases ---
  { text: "Wind so strong it blew the motivation right out of you.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "Your carefully styled hair just became abstract art.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "Windy enough that opening the front door is a two-hand job.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "The wind stole your grocery receipt and it's gone forever.", conditions: ["wind"], tempRange: null, priority: 2 },
  { text: "Gusts that make you lean sideways like a mime. Except it's real.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "The wind is whistling through your car like a haunted house soundtrack.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "Windy day. Every skirt and dress is a liability.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "The wind just relocated your neighbor's trampoline. Again.", conditions: ["wind"], tempRange: null, priority: 2 },
  { text: "Wind advisory. Your garbage cans are going on a world tour.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "It's blowing so hard you typed this text message three words at a time between gusts.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "Windy enough to make a grown adult sprint for the parking garage.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "Your outdoor decorations are now your neighbor's outdoor decorations.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "Wind so fierce your eyes are watering and you look emotional.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "The wind sounds angry. Like really personally offended.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "Gusting hard. Every paper bag in the parking lot has gone airborne.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "Windy enough that your ponytail is basically a weapon.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "The wind knocked over your bike. Then your other bike. It's personal.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "Blowing hard enough that you can hear your roof questioning its commitment.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "Wind turning every crosswalk into a sprint challenge.", conditions: ["wind"], tempRange: null, priority: 1 },
  { text: "The wind is that special kind of cold-gusty combo that hits your soul.", conditions: ["wind"], tempRange: null, priority: 1 },

  // ============================================================
  // FREEZING RAIN (25 phrases)
  // ============================================================
  { text: "Freezing rain. The roads are now an ice rink nobody asked for.", conditions: ["freezing-rain"], tempRange: null, priority: 2 },
  { text: "It's raining and freezing. Pick your favorite way to slip.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "Freezing rain turning everything into a death trap. Walk like a penguin.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "Ice is forming on everything. Your driveway has become a lawsuit.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "Freezing rain. Nature's way of adding a difficulty level to your commute.", conditions: ["freezing-rain"], tempRange: null, priority: 2 },
  { text: "Every surface is now ice. Trust nothing. Suspect everything.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "Freezing rain advisory. Your car is now wearing an ice suit.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "The rain is freezing on contact. Your windshield has opinions about that.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "Freezing rain. Today's forecast: ice, regret, and bruises.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "It's sleeting. The worst of rain and ice teamed up against you.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  // --- 15 NEW freezing rain phrases ---
  { text: "Freezing rain. Your front steps just became an Olympic luge track.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "Everything is glazed in ice. Not the donut kind.", conditions: ["freezing-rain"], tempRange: null, priority: 2 },
  { text: "Freezing rain advisory. The salt truck is your new best friend.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "Ice on everything. Your car door handle is now a puzzle.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "Freezing rain. Every step outside is a gamble with your tailbone.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "The freezing rain coated your windshield in a quarter inch of spite.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "Sleet and freezing rain. The commute is now an extreme sport.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "Freezing rain. Your wipers are frozen to the windshield. Good morning.", conditions: ["freezing-rain"], tempRange: null, priority: 2 },
  { text: "Ice everywhere. Walking to the mailbox requires a risk assessment.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "Freezing rain has turned your sidewalk into a slip-and-slide of regret.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "The trees look beautiful covered in ice. The roads do not.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "Freezing rain. Even the mail carrier skipped your block.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "Everything is encased in ice like a very inconvenient snow globe.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "Freezing rain turned the parking lot into a demolition derby qualifier.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },
  { text: "Ice storm in progress. Your doorknob is frozen and your patience is next.", conditions: ["freezing-rain"], tempRange: null, priority: 1 },

  // ============================================================
  // EXTREME HEAT (25 phrases) - clear + high temp
  // ============================================================
  { text: "It's [temp] degrees. The pavement could cook your breakfast.", conditions: ["clear"], tempRange: [96, 130], priority: 2 },
  { text: "[temp] degrees. Satan just checked the weather here and said 'damn.'", conditions: ["clear"], tempRange: [96, 130], priority: 2 },
  { text: "It's a tad warm at [temp] degrees. Like, surface-of-the-sun warm.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "[temp] degrees. Your car is a kiln. Your steering wheel is a branding iron.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "At [temp] degrees, even your sweat is sweating.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "[temp] degrees outside. Breathing counts as a hot yoga session.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "The heat index is [temp]. The heat index has lost its mind.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "[temp] degrees. Going outside is now a medical decision.", conditions: ["clear"], tempRange: [96, 130], priority: 2 },
  { text: "It is [temp] degrees and everything is stupid.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "[temp] degrees. The birds are using potholders.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  // --- 15 NEW extreme heat phrases ---
  { text: "[temp] degrees. Your ice cream didn't make it from the store to the car.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "It's [temp] degrees and the asphalt is soft. Literally melting.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "[temp] degrees. Walking to the mailbox counts as cardio today.", conditions: ["clear"], tempRange: [96, 130], priority: 2 },
  { text: "At [temp] degrees your phone just shut itself off to protect its dignity.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "[temp] degrees. The pool water is warm. The pool water is not refreshing.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "It's [temp] degrees and your deodorant surrendered before noon.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "[temp] degrees. The sun is not your friend. The sun is your landlord.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "A scorching [temp] degrees. Your flip-flops are bonding with the pavement.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "[temp] degrees and the only thing moving outside is heat shimmer.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "It's [temp] degrees. Every fire hydrant is a potential water park.", conditions: ["clear"], tempRange: [96, 130], priority: 2 },
  { text: "[temp] degrees. Your electric bill just entered the stratosphere.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "At [temp] degrees you can feel the heat through your shoes.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "[temp] degrees. Eggs are frying on sidewalks and it's not a metaphor.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "It's [temp] damn degrees. Even the lizards are looking for shade.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },
  { text: "[temp] degrees. The weather just declared war on productivity.", conditions: ["clear"], tempRange: [96, 130], priority: 1 },

  // ============================================================
  // EXTREME COLD (25 phrases) - any + sub-zero
  // ============================================================
  { text: "[temp] degrees. Your nostalgia for summer has never been stronger.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "It's [temp] degrees. Frostbite is not a personality trait, go inside.", conditions: ["any"], tempRange: [-50, 0], priority: 2 },
  { text: "[temp] degrees. Even your phone battery is giving up.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "Below zero at [temp] degrees. Your eyelashes are freezing together.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "[temp] degrees outside. The air hurts your face. Why do you live here.", conditions: ["any"], tempRange: [-50, 0], priority: 2 },
  { text: "It's [temp] damn degrees. Exposed skin freezes in minutes. Stay inside.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "[temp] degrees. Cold enough to question every life decision that led you here.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "At [temp] degrees, your car might not start and honestly same.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "[temp] degrees. Boiling water would freeze before hitting the ground.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "The temperature is [temp]. That's not weather, that's an emergency.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  // --- 15 NEW extreme cold phrases ---
  { text: "[temp] degrees. Your nostrils just froze shut on the first breath.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "It's [temp] degrees and your car is making sounds it's never made before.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "[temp] degrees. The walk from the car to the door feels like an arctic expedition.", conditions: ["any"], tempRange: [-50, 0], priority: 2 },
  { text: "At [temp] degrees your coffee went from hot to iced before you reached the office.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "[temp] degrees. Even the snowmen look cold.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "It's [temp] degrees and your heating bill is now your entire personality.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "[temp] degrees. Cold enough that your teeth hurt just standing outside.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "At [temp] degrees the only acceptable plans are under a blanket.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "[temp] degrees. Your pipes might freeze. Your will to live already did.", conditions: ["any"], tempRange: [-50, 0], priority: 2 },
  { text: "It's [temp] degrees. Three layers isn't enough. Nothing is enough.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "[temp] degrees. Your garage door sounds like a dying robot.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "At [temp] degrees even the dog's walk lasted thirty seconds.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "[temp] degrees. You can see your breath and your regrets.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "It's [temp] degrees and the gas station pump handle might take your skin off.", conditions: ["any"], tempRange: [-50, 0], priority: 1 },
  { text: "[temp] degrees. Hell didn't freeze over but everything else did.", conditions: ["any"], tempRange: [-50, 0], priority: 2 },

  // ============================================================
  // PARTLY CLOUDY (23 phrases)
  // ============================================================
  { text: "Partly cloudy. The sky can't commit to a look today.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Sun and clouds playing peekaboo. How delightful. How annoying.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Partly cloudy, partly sunny, fully indecisive.", conditions: ["partly-cloudy"], tempRange: null, priority: 2 },
  { text: "The sun keeps ducking behind clouds like it owes you money.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Half the sky is sunny, half is gray. Pick a lane, atmosphere.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Scattered clouds with occasional bursts of false hope.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "The weather is giving mixed signals. Classic.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Partly cloudy. Sunglasses on, sunglasses off, repeat forever.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  // --- 15 NEW partly cloudy phrases ---
  { text: "The clouds keep photobombing the sun.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Partly cloudy. The sky is doing that thing where it can't pick a vibe.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Sun, then shade, then sun again. Your pupils are exhausted.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Partly cloudy with a chance of 'why did I bring sunglasses.'", conditions: ["partly-cloudy"], tempRange: null, priority: 2 },
  { text: "The sun is playing hard to get behind those clouds.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Scattered clouds that only show up when you're trying to sunbathe.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Partly cloudy. Your shadow keeps appearing and disappearing like a magician.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "The sky is half sunny, half moody. The weather has range today.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Sun peeking through clouds like it's checking if you're having fun.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Partly cloudy. Not enough sun to commit to the beach. Not enough cloud for an excuse.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Clouds drifting by like the sky is scrolling through its thoughts.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Partly cloudy. The perfect weather for arguing about whether it's nice out.", conditions: ["partly-cloudy"], tempRange: null, priority: 2 },
  { text: "The sun is on a part-time schedule today.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Some sun, some clouds, zero commitment from the sky.", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },
  { text: "Partly cloudy. The forecast equivalent of 'it's complicated.'", conditions: ["partly-cloudy"], tempRange: null, priority: 1 },

  // ============================================================
  // COMBINATION (38 phrases) - mixed conditions + temp ranges
  // ============================================================
  { text: "Rainy and [temp] degrees. A wet, cold hug from the atmosphere.", conditions: ["rain", "drizzle"], tempRange: [35, 50], priority: 1 },
  { text: "[temp] degrees with thunderstorms. The sky is angry AND it's hot. Great.", conditions: ["thunderstorm"], tempRange: [80, 100], priority: 1 },
  { text: "Snowing at [temp] degrees. This is the kind of cold that builds character, apparently.", conditions: ["snow", "heavy-snow"], tempRange: [0, 25], priority: 1 },
  { text: "Windy and [temp] degrees. The wind chill is a whole different level of betrayal.", conditions: ["wind"], tempRange: [10, 30], priority: 1 },
  { text: "Foggy and [temp] degrees. Can't see and can't feel your fingers. Perfect.", conditions: ["fog"], tempRange: [25, 40], priority: 1 },
  { text: "Cloudy at [temp] degrees. Even the sun didn't want to deal with this crap.", conditions: ["cloudy"], tempRange: [30, 45], priority: 1 },
  { text: "Hot and rainy at [temp] degrees. Congratulations, you live in a sauna.", conditions: ["rain", "heavy-rain"], tempRange: [80, 95], priority: 2 },
  { text: "It's [temp] degrees and snowing sideways. This is fine. Everything is fine.", conditions: ["snow", "heavy-snow", "wind"], tempRange: [-10, 20], priority: 1 },
  { text: "Thunderstorms at [temp] degrees. Warm enough to sweat, stormy enough to cry.", conditions: ["thunderstorm"], tempRange: [75, 95], priority: 1 },
  { text: "Clear skies but [temp] degrees. The sun is out but so is your misery.", conditions: ["clear"], tempRange: [1, 20], priority: 1 },
  { text: "Partly cloudy and [temp] degrees. At least pick a struggle, weather.", conditions: ["partly-cloudy"], tempRange: [40, 60], priority: 1 },
  { text: "Wind and rain at [temp] degrees. Your umbrella was never going to make it.", conditions: ["rain", "wind"], tempRange: [40, 60], priority: 1 },
  { text: "Fog at [temp] degrees with drizzle. Visibility and morale both at zero.", conditions: ["fog", "drizzle"], tempRange: [35, 50], priority: 1 },
  { text: "Cloudy, windy, and [temp] degrees. The weather trifecta of misery.", conditions: ["cloudy", "wind"], tempRange: [25, 40], priority: 1 },
  { text: "Heavy rain at [temp] degrees. Your shoes are already mourning.", conditions: ["heavy-rain"], tempRange: [45, 65], priority: 1 },
  { text: "Snow and wind at [temp] degrees. Visibility is just a suggestion.", conditions: ["snow", "wind"], tempRange: [5, 25], priority: 1 },
  { text: "Freezing rain at [temp] degrees. The world is a skating rink and you didn't sign up.", conditions: ["freezing-rain"], tempRange: [20, 33], priority: 1 },
  { text: "Drizzle at [temp] degrees. Too warm for snow, too cold for dignity.", conditions: ["drizzle"], tempRange: [33, 42], priority: 1 },
  // --- 20 NEW combination phrases ---
  { text: "Foggy and [temp] degrees. Your morning jog just became a horror movie jog.", conditions: ["fog"], tempRange: [30, 50], priority: 1 },
  { text: "Rain and [temp] degrees. Your leather seats are making noises they shouldn't.", conditions: ["rain", "heavy-rain"], tempRange: [75, 90], priority: 1 },
  { text: "Windy at [temp] degrees. The windchill makes it feel like a personal attack.", conditions: ["wind"], tempRange: [20, 40], priority: 1 },
  { text: "Cloudy and [temp] degrees. The weather is as uninspired as your lunch.", conditions: ["cloudy"], tempRange: [50, 65], priority: 1 },
  { text: "Snow at [temp] degrees. Your car's defrost is going to need a full hour.", conditions: ["snow"], tempRange: [-10, 15], priority: 2 },
  { text: "Thunderstorms and [temp] degrees. A humid, electric mess out there.", conditions: ["thunderstorm"], tempRange: [85, 100], priority: 1 },
  { text: "Partly cloudy and [temp] degrees. The definition of 'meh' weather.", conditions: ["partly-cloudy"], tempRange: [55, 70], priority: 1 },
  { text: "Drizzle at [temp] degrees. Warm rain on your windshield like nature is spitting.", conditions: ["drizzle"], tempRange: [70, 85], priority: 1 },
  { text: "Freezing rain at [temp] degrees. Your sidewalk salt is working overtime.", conditions: ["freezing-rain"], tempRange: [25, 33], priority: 1 },
  { text: "Wind and snow at [temp] degrees. Whiteout conditions and zero chill, figuratively.", conditions: ["wind", "snow"], tempRange: [-5, 18], priority: 1 },
  { text: "Heavy rain and [temp] degrees. The humidity is a separate weather event.", conditions: ["heavy-rain"], tempRange: [78, 92], priority: 1 },
  { text: "Fog and [temp] degrees. Your car's sensors are having an existential crisis.", conditions: ["fog"], tempRange: [32, 45], priority: 1 },
  { text: "Cloudy, drizzly, and [temp] degrees. Peak 'cancel all plans' weather.", conditions: ["cloudy", "drizzle"], tempRange: [40, 55], priority: 2 },
  { text: "Snow and [temp] degrees. The windshield scraper you lost in October would be real handy.", conditions: ["snow"], tempRange: [5, 28], priority: 1 },
  { text: "Wind and [temp] degrees. Your face is numb and your hair is a crime scene.", conditions: ["wind"], tempRange: [5, 25], priority: 1 },
  { text: "Rain and fog at [temp] degrees. Nature combined the worst settings.", conditions: ["rain", "fog"], tempRange: [38, 55], priority: 1 },
  { text: "Partly cloudy and [temp] degrees. Comfortable enough that you have no excuse to skip the gym.", conditions: ["partly-cloudy"], tempRange: [62, 78], priority: 1 },
  { text: "Thunderstorms at [temp] degrees and the power just flickered twice.", conditions: ["thunderstorm"], tempRange: [65, 80], priority: 1 },
  { text: "Snow, wind, and [temp] degrees. Nature threw everything at the wall today.", conditions: ["snow", "wind"], tempRange: [-15, 10], priority: 2 },
  { text: "Heavy rain at [temp] degrees. Your basement is about to become a pool.", conditions: ["heavy-rain"], tempRange: [50, 70], priority: 1 },
];
